name: Java CI with Maven
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11
        server-id: danodic.dev-jao-java
        server-username: PACKAGES_USERNAME
        server-password: PACKAGES_TOKEN
    - name: Build
      run: mvn compile -DskipTests
      env:
        PACKAGES_USERNAME: ${{ secrets.PACKAGES_USERNAME }}
        PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
    - name: Sonarqube Scan
      run: mvn verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
    - name: Publish to GitHub Packages
      run: mvn --batch-mode deploy  -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
