name: Java CI with Maven
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      run: mvn compile -DskipTests
    - name: Sonarqube Scan
      run: mvn verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
    - name: Publish to GitHub Packages
      run: mvn --batch-mode deploy  -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
